apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "demo1-openapi"
  title: "demo1-openapi"
  description: "Demo1 openapi"
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/llowinge/spectral-rules/main/ruleset.yaml
  links:
    - url: https://registry-apicurio-registry.apps.cluster-x56f8.x56f8.sandbox2954.opentlc.com/ui/artifacts/com.redhat/demo1-openapi/versions/latest
      title: Apicurio Registry
      icon: web
    - url: https://microcks-microcks.apps.cluster-x56f8.x56f8.sandbox2954.opentlc.com/#/services?name=demo1-openapi
      title: Microcks
    - url: https://microcks-microcks.apps.cluster-x56f8.x56f8.sandbox2954.opentlc.com/rest/ratings/v1
      title: Mock
      icon: web
spec:
  type: openapi
  system: system:default/demo1
  owner: "group:default/backstage-admins"
  lifecycle: production
  definition:
    $openapi: https://github.com/llowinge/demo1-demo1-openapi-api/blob/main/specification.yaml